### ISSUE TITLE
creation d'event 415

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#106]
Optional({
    error = "Unsupported Media Type";
    message = "Content type 'multipart/form-data;boundary=alamofire.boundary.b37fb67ace082076;charset=UTF-8' not supported";
    path = "/event/";
    status = 415;
    timestamp = "2019-08-27T13:58:09.502+0000";
})

**Comment by SBRKH** [comment]
Ne pas envoyer un mutlipart/form-data mais un body json

**Comment by SBRKH** [comment]
+ /event pas /event/
