### ISSUE TITLE
500 change email

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#110]
Optional({
  "error" : "Internal Server Error",
  "path" : "\/users\/me\/parameter\/email",
  "message" : "Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction",
  "timestamp" : "2019-09-04T12:02:02.917+0000",
  "status" : 500
})

**Comment by SBRKH** [comment]
Tester en local avec users/me/parameter/email?email=sabri.khoualdia@epitech.eu :

> {
    "success": true,
    "message": "La ressource a bien été mise à jour",
    "payload": true,
    "httpStatus": "ACCEPTED",
    "code": 202,
    "status": 202
}
