### ISSUE TITLE
create event 500

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#113]
Optional({
  "status" : 500,
  "error" : "Internal Server Error",
  "timestamp" : "2019-09-04T14:43:00.596+0000",
  "path" : "\/event",
  "message" : "could not execute statement; SQL [n\/a]; constraint [event_pkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
})

**Comment by SBRKH** [comment]
Quel est ton payload ? J'ai pas d'erreur
