### ISSUE TITLE
get event by title mauvais events return

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#114]
Peu importe ce que je tape pour title ça renvoie toujours les événements que t'as créé:
Ex: j'ai tapé Ultra Miami j'ai eu:

Optional({
  "message" : "La requête a été traîtée avec succès",
  "payload" : [
    {
      "id" : 1,
      "shortDescription" : "tatetate",
      "end" : "23\/09\/2019 08:00",
      "eventPicture" : null,
      "name" : "J'ai failli oublié le nom lool"
    },
    {
      "id" : 2,
      "shortDescription" : "tatetate",
      "end" : "18\/01\/2020 12:00",
      "eventPicture" : null,
      "name" : "J'ai failli oublié le nom lool"
    }
  ],
  "status" : 200,
  "code" : 200,
  "success" : true,
  "httpStatus" : "OK"
})

**Comment by SBRKH** [comment]
http://localhost:8080/event/search?title=Ultra Miami me retourne rien
http://localhost:8080/event/search?title=4 =>
{
    "success": true,
    "message": "La requête a été traîtée avec succès",
    "payload": [
        {
            "id": 1,
            "name": "Test 4",
            "shortDescription": "MONGEGEGEGEGE",
            "eventPicture": null,
            "end": "21/09/2019 00:00"
        }
    ],
    "httpStatus": "OK",
    "code": 200,
    "status": 200
}

**Comment by FakeAK** [comment]
Je sais pas pourquoi j'ai re-testé et ça marche, je réouvrirai si j'ai de nouveau le pb
