### ISSUE TITLE
Change email 500

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#116]
Quand je change d'adresse email et que j'en met une qui est déjà prise ça renvoie une 500
Faudrait fix ça et dans l'idéal renvoyer une 400+

**Comment by SBRKH** [comment]
Normal t'es pas censé pouvoir assigner une adresse mail déjà utilisé.
Pour la 500 je dois regarder pourquoi mes codes d'erreur sont pas renvoyés

**Comment by SBRKH** [comment]
cf issue #109
