### ISSUE TITLE
event participation 500

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#118]
Quand je suis déjà intéressé (ou participe) à un event : 
{
  "path" : "\/event\/7\/users\/5\/participation",
  "message" : "Event Participation already exist",
  "timestamp" : "2019-09-07T15:39:57.529+0000",
  "error" : "Internal Server Error",
  "status" : 500
}

le code d'erreur comme d'hab est pas bon mdr

**Comment by SBRKH** [comment]
see #109
