### ISSUE TITLE
users/userid/profile/search?name=

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#124]
Quand je tape Dan ça me renvoie bien Dan, et quand je l'ajoute ça l'ajoute bien
Mais après quand je retape Dan, le endpoint me ressort Dan alors que je l'ai déjà ajouté et sans m'avertir que je l'ai déjà ajouté donc quand je le rajoute j'ai une erreur 500 déjà ajouté

Donc faudrait soit:
- Ne pas ressortir Dan (meilleure option)
- Ressortir Dan mais m'informer que je l'ai déjà ajouté pour que coté front je bloque le bouton d'ajout

**Comment by SBRKH** [comment]
Je l'enlève du payload si vous êtes amis .
