### ISSUE TITLE
EZ feature

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#129]
Quand on t'envoie pas d'image dans le formulaire de création d'event, mettre le lien d'une image par défaut comme ça on a tous la même pour:
- banner_picture
- event_picture
- thumbnails_picture

**Comment by SBRKH** [comment]
Supprimer l'username

**Comment by SBRKH** [comment]
Supprimer le filtre smoke

**Comment by SBRKH** [comment]
commit d465b81
commit 4e31d8c
