### ISSUE TITLE
500 Delete Account

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#80]
Optional({
    error = "Internal Server Error";
    message = "could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement";
    path = "/api/user/parameter/delete";
    status = 500;
    timestamp = 1556667096499;
})

**Comment by SBRKH** [comment]
Pas réussi à reproduire (peut-être que c'est déjà fix mais pas encore push sur le vps :-))
