### ISSUE TITLE
500 get event by title

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#83]
Optional({
    error = "Internal Server Error";
    message = "Event with id 1636688131 doesn't exist";
    path = "/api/event/1636688131";
    status = 500;
    timestamp = 1556842026348;
})

**Comment by SBRKH** [comment]
> path = "/api/event/1636688131";
t'as pas fait l'appel par title mais par id, pour le title c'est sous la forme

> "/api/event/?title=
