### ISSUE TITLE
500 Edit profile

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#84]
Optional({
    error = "Internal Server Error";
    message = "query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2";
    path = "/api/user/profil/24";
    status = 500;
    timestamp = 1556886319778;
})

**Comment by FakeAK** [comment]
Ok c'est normal en fait, mais le message d'erreur peut être mieux parce qu'on comprend pas là, le bug c'était que j'avais la même email qu'un autre compte, c'est pas une 500 mais une 400

**Comment by SBRKH** [comment]
Le message d'erreur ne vient pas de moi mais de Hibernate donc je peux rien y faire
