### ISSUE TITLE
Rendre l'email optionnel dans la requete d'edit profile

### ISSUE THREAD

**Issue by FakeAK** [SBRKH/nox_api#85]
Je change pas l'email ici du coup ce field m'embête un peu à cet endroit parce que j'ai pas forcément l'email du user (par ex dans le futur si il se connecte avec facebook ou whatever service qui nous donne pas son email)

**Comment by SBRKH** [comment]
T'as l'email dans le payload renvoyait à la connexion, tu l'auras aussi si l'user se connecte avec fb ou autre (ce qui est pas près d'arriver)

**Comment by FakeAK** [comment]
Non l'email est pas obligatoire quand on se connecte avec fb, le user peut choisir de pas le transmettre au service fait le test co toi avec fb à un truc truc et quand facebook te dit ce que recevra l'app tu appuies sur "Modifier ça" et tu décoches email et l'app recevra pas ton email, donc tôt ou tard faudra réouvrir cette issue parce qu'on aura pas toujours l'email du user
